# Generated by Django 5.0.7 on 2024-08-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0002_userprofile_lastname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="days_of_week",
            field=models.CharField(max_length=27),
        ),
    ]
