# Generated by Django 5.0.7 on 2024-08-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0003_alter_activity_days_of_week"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitylog",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="start_time",
        ),
        migrations.AddField(
            model_name="activitylog",
            name="marked",
            field=models.BooleanField(default=False),
        ),
    ]
