# Generated by Django 5.0.7 on 2024-08-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0004_remove_activitylog_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="active",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="end_time",
        ),
    ]
