# Generated by Django 5.0.7 on 2024-08-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0005_remove_activity_active_remove_activity_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="days_of_week",
            field=models.CharField(max_length=50),
        ),
    ]
