# Generated by Django 5.0.7 on 2024-11-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0006_alter_activity_days_of_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
