# Generated by Django 5.0.7 on 2024-11-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0007_activity_end_date_activity_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitylog",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="marked",
        ),
        migrations.AddField(
            model_name="activitylog",
            name="status",
            field=models.CharField(
                choices=[("✔️", "Completed"), ("❌", "Missed")],
                default="❌",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
