# Generated by Django 5.0.7 on 2024-11-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0009_activitylog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("✔️", "Completed"), ("❌", "Missed")],
                max_length=10,
                null=True,
            ),
        ),
    ]
