# Generated by Django 5.0.7 on 2024-12-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0011_alter_activity_days_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="days_of_week",
            field=models.CharField(max_length=50),
        ),
    ]
