# Generated by Django 5.0.7 on 2025-01-16 23:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prime", "0014_activityexclusion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activitylog",
            unique_together={("activity", "user", "date")},
        ),
    ]
